### ISSUE TITLE
2021分支运行am-kernels时编译错误。

### ISSUE THREAD

**Issue by leon8086** [NJU-ProjectN/ics2017#11]
使用2021分支，nemu使用默认设置并make。

拉取am-kernels并用make ARCH=native mainargs=k run运行am_kernels/test/am-tests时，报编译错误：

In file included from /xxx/abstract-machine/am/src/native/vme.c:3:
/xxx/abstract-machine/am/src/native/platform.h:23:11: error: variably modified ‘sigstack’ at file scope
   23 |   uint8_t sigstack[SIGSTKSZ];
      |           ^~~~~~~~

注释掉#define _GNU_SOURCE，错误解决，但出现新错误：
/xxx/abstract-machine/am/src/native/vme.c:17:23: error: field ‘hash’ has incomplete type
   17 |   struct hsearch_data hash;
      |                       ^~~~
/xxx/abstract-machine/am/src/native/vme.c: In function ‘protect’:
/xxx/abstract-machine/am/src/native/vme.c:42:13: error: implicit declaration of function ‘hcreate_r’; did you mean ‘hcreate’? [-Werror=implicit-function-declaration]
   42 |   int ret = hcreate_r(max_pg, &h->hash);
      |             ^~~~~~~~~
      |             hcreate
/xxx/abstract-machine/am/src/native/vme.c: In function ‘map’:
/xxx/abstract-machine/am/src/native/vme.c:96:3: error: implicit declaration of function ‘hsearch_r’; did you mean ‘hsearch’? [-Werror=implicit-function-declaration]
   96 |   hsearch_r(item, FIND, &item_find, &vm_head->hash);
      |   ^~~~~~~~~
      |   hsearch

替换include次序：
#include "platform.h"
#define _GNU_SOURCE
#include <search.h>

问题照旧。
是否是我环境设置有问题呢？环境是Ubuntu22.04LTS，llvm降级到v11。

**Comment by goupeng2333** [comment]
已收到

**Comment by sashimi-yzh** [comment]
请参考这个修改 https://github.com/NJU-ProjectN/abstract-machine/commit/112799e02a28d22f03cfe496fe36408112047a71

**Comment by leon8086** [comment]
已解决
