### ISSUE TITLE
ics2015中的疑问

### ISSUE THREAD

**Issue by PorterLu** [NJU-ProjectN/ics2017#12]
你好敬爱的yzh，
在NJU ics2015 PA2的lab中需要使用binary scaling实现浮点，但是我发现在实现FLOAT浮点后出现了0xd9等不能识别的opcode，怀疑是引入了float变量出现的问题。
怀疑的理由如下：1.我已经遵照i386手册实现了实验指令通过了之前除了浮点和字符输出的全部程序，并且参照了i386的operation说明。2.在指令的实现中，我已经花费了两周检查和学习，出错的概率很小，并且执行过程中使用了单步执行进行检查。3.在2021的PA中删除了对integral.c和quadratic.c的测试。4.在查询github中ics 2015的实现中，很多人为了实现浮点引入了其他库文件，这时实验手册中没有说明的。
x87指令的出现似乎成为了了不可避免地情况，2015的实验手册似乎也没写这种情况

**Comment by sashimi-yzh** [comment]
你好, 老版本的实验内容已经不维护了

**Comment by PorterLu** [comment]
有办法解决浮点问题吗，我可能只能实现一下简单的浮点指令了吗，当年的同学有什么解决方案吗

**Comment by sashimi-yzh** [comment]
快10年前的实验内容, 我们很早就不使用了...

**Comment by PorterLu** [comment]
好的，我会越过浮点的内容，主要ics2015还有dram等模块的模拟，而2021版中删除了，本来是准备实现完2015后再去2021版的，谢谢yzh
