### ISSUE TITLE
MacOS上, `_KEY_T` 与 `sys/_types/_key_t.h` 冲突

### ISSUE THREAD

**Issue by silver-ymz** [NJU-ProjectN/ics2017#18]
在`nemu/src/device/keyboard.c`文件中, 第38行`MAP(_KEYS, _KEY_NAME)`会定义`_KEY_T`, 与MacOS SDK中`sys/_types/_key_t.h`冲突.

`sys/_types/_key_t.h`文件内容为
```
#ifndef _KEY_T
#define _KEY_T
#include <machine/types.h> /* __int32_t */
typedef __int32_t        key_t;         /* IPC key (for Sys V IPC) */
#endif  /* _KEY_T */
```

需要在定义该enum前, `#undef _KEY_T`

**Comment by goupeng2333** [comment]
已收到

**Comment by sashimi-yzh** [comment]
感谢指出问题!

你可以把这个undef放在一个和MacOS相关的条件编译中, 然后提交一个PR.
