### ISSUE TITLE
2022分支选择x86作为ISA会编译报错

### ISSUE THREAD

**Issue by Kinyi** [NJU-ProjectN/ics2017#19]
ics-pa项目选择2022分支，init nemu项目后，通过make menuconfig切换到x86 ISA，接着编译就会发生报错
![3](https://user-images.githubusercontent.com/11610044/227721793-901011d2-243a-4c62-bd1a-3381677742df.png)

提示nemu/src/isa/x86目录找不到。ics-pa的2022分支是checkout nemu项目的ics2022分支，确实是没有该目录，而ics2020分支就存在该目录。而2022版讲义中显示的目录结构是有x86目录的，请老师指导一下，谢谢
![1 5](https://user-images.githubusercontent.com/11610044/227722290-22bf2007-e4aa-4795-98aa-b3b614c72a23.png)
![1](https://user-images.githubusercontent.com/11610044/227722296-6b79a0ae-a95e-46a4-b22c-8255705670ba.png)
![2](https://user-images.githubusercontent.com/11610044/227722303-eb4c9203-20ff-4a96-83e4-f1db0bc0ce61.png)

**Comment by sashimi-yzh** [comment]
目前版本不支持x86, 两年前重构代码后, 我一直没时间加回来. 如果想做x86, 可以做ics2020版本.

**Comment by Kinyi** [comment]
好的，谢谢老师
