### ISSUE TITLE
关于表达式生成的疑问

### ISSUE THREAD

**Issue by ljxrrcj** [NJU-ProjectN/ics2017#21]
用于表达式生成 .code.c 似乎只能保证结果为无符号数，但无法保证中间过程也遵循无符号运算，但是实验内容要求表达式求值过程中均进行无符号运算，两者似乎冲突了？
以表达式 （ 6 / -3 ）和表达式（ 6 / （1 - 4 ））为例，.code.c的结果是 4294967294，但如果在表达式求值的过程中将 -3 作为一个无符号数进行运算的话，结果应该为 0。
有什么相关的资料可供参考吗？还望各位大佬指点迷津。

**Comment by sashimi-yzh** [comment]
这是一个C语言问题, 如果你确实想不出解决方案, 可以考虑查阅一些C语言的资料并复习一下其中的细节, 这个过程应该也能帮助你查缺补漏.

**Comment by ljxrrcj** [comment]
> 这是一个C语言问题, 如果你确实想不出解决方案, 可以考虑查阅一些C语言的资料并复习一下其中的细节, 这个过程应该也能帮助你查缺补漏.

我想我找到解决方案了，感谢指导。
