### ISSUE TITLE
I suggest that the init.sh add newline before and after environment variable settings

### ISSUE THREAD

**Issue by kkzxak47** [NJU-ProjectN/ics2017#28]
or the .bashrc could end up like this
![Screenshot_2024-05-18_12-50-42](https://github.com/NJU-ProjectN/ics-pa/assets/2363326/dab39fb1-e071-4d07-92f7-64689451620b)

**Comment by sashimi-yzh** [comment]
Would you please submit a pull request?

**Comment by sashimi-yzh** [comment]
Fix in commit f5f23e1a43d24a0b2191f943d74d0c024dae6357.
