### ISSUE TITLE
2017版  nexus-am编译问题

### ISSUE THREAD

**Issue by nefiend** [NJU-ProjectN/ics2017#3]
ics@c993c8a57129:~/hhh/ics-pa/nexus-am/tests/cputest$ make ARCH=x86-nemu ALL=dummy run  
Building dummy [x86-nemu]
+ CC tests/dummy.c
Building am [x86-nemu]
**make[2]: *** No targets specified and no makefile found.  Stop.**
[src/monitor/monitor.c,65,load_img] The image is /home/ics/hhh/ics-pa/nexus-am/tests/cputest/build/dummy-x86-nemu.bin
Welcome to NEMU!
[src/monitor/monitor.c,30,welcome] Build time: 16:24:17, Sep 18 2018
For help, type "help"
(nemu) 

问题大概是nexus-am目录下的Makefile.compile文件最后一行编译问题，应该是nexus-am\libs\klib 直接给的.a文件而没有src文件，与2018版本有不同，请查看一下

**Comment by sashimi-yzh** [comment]
確實是因為提供.a引起的, 但程序可以正常編譯鏈接, 因此可以忽略這個錯誤信息.
