### ISSUE TITLE
请问一下2018版ramdisk的链接问题

### ISSUE THREAD

**Issue by bsblcc** [NJU-ProjectN/ics2017#4]
在pa3生成ramdisk时, native和x86-nemu都会出现未定义的引用:
native的:
`tumblingdice@tumblingdice-PC:~/Documents/nemu/nanos-lite$ make ARCH=native update
Building nanos-lite [native] with AM_HOME {/home/tumblingdice/Documents/nemu/nexus-am}
make -s -C /home/tumblingdice/Documents/nemu/navy-apps ISA=am_native
+ LD /home/tumblingdice/Documents/nemu/navy-apps/apps/init/build/init-am_native
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(svfscanf.o)：在函数‘__ssvfscanf_r’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdio/vfscanf.t:1889：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(strtod.o)：在函数‘_strtod_l’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:454：对‘nan’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(strtod.o)：在函数‘strtof_l’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1292：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1292：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(strtod.o)：在函数‘strtof’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1307：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1307：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(execr.o)：在函数‘_fork_r’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/reent/execr.c:88：对‘_fork’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(execr.o)：在函数‘_wait_r’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/reent/execr.c:120：对‘_wait’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/Makefile.app:36: recipe for target '/home/tumblingdice/Documents/nemu/navy-apps/apps/init/build/init-am_native' failed
make[2]: *** [/home/tumblingdice/Documents/nemu/navy-apps/apps/init/build/init-am_native] Error 1
+ LD /home/tumblingdice/Documents/nemu/navy-apps/apps/pal/build/pal-am_native
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(svfscanf.o)：在函数‘__ssvfscanf_r’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdio/vfscanf.t:1889：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(strtod.o)：在函数‘_strtod_l’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:454：对‘nan’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(strtod.o)：在函数‘strtof_l’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1292：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1292：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(strtod.o)：在函数‘strtof’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1307：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1307：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/Makefile.app:36: recipe for target '/home/tumblingdice/Documents/nemu/navy-apps/apps/pal/build/pal-am_native' failed
make[2]: *** [/home/tumblingdice/Documents/nemu/navy-apps/apps/pal/build/pal-am_native] Error 1
+ LD /home/tumblingdice/Documents/nemu/navy-apps/apps/litenes/build/litenes-am_native
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(svfscanf.o)：在函数‘__ssvfscanf_r’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdio/vfscanf.t:1889：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(strtod.o)：在函数‘_strtod_l’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:454：对‘nan’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(strtod.o)：在函数‘strtof_l’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1292：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1292：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(strtod.o)：在函数‘strtof’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1307：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1307：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/Makefile.app:36: recipe for target '/home/tumblingdice/Documents/nemu/navy-apps/apps/litenes/build/litenes-am_native' failed
make[2]: *** [/home/tumblingdice/Documents/nemu/navy-apps/apps/litenes/build/litenes-am_native] Error 1
+ LD /home/tumblingdice/Documents/nemu/navy-apps/tests/bmp/build/bmptest-am_native
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(svfscanf.o)：在函数‘__ssvfscanf_r’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdio/vfscanf.t:1889：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(strtod.o)：在函数‘_strtod_l’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:454：对‘nan’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(strtod.o)：在函数‘strtof_l’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1292：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1292：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(strtod.o)：在函数‘strtof’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1307：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1307：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/Makefile.app:36: recipe for target '/home/tumblingdice/Documents/nemu/navy-apps/tests/bmp/build/bmptest-am_native' failed
make[2]: *** [/home/tumblingdice/Documents/nemu/navy-apps/tests/bmp/build/bmptest-am_native] Error 1
+ LD /home/tumblingdice/Documents/nemu/navy-apps/tests/dummy/build/dummy-am_native
+ LD /home/tumblingdice/Documents/nemu/navy-apps/tests/events/build/events-am_native
+ LD /home/tumblingdice/Documents/nemu/navy-apps/tests/hello/build/hello-am_native
+ LD /home/tumblingdice/Documents/nemu/navy-apps/tests/text/build/text-am_native
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(vfscanf.o)：在函数‘__svfscanf_r’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdio/vfscanf.t:1889：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(strtod.o)：在函数‘_strtod_l’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:454：对‘nan’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(strtod.o)：在函数‘strtof_l’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1292：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1292：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-am_native.a(strtod.o)：在函数‘strtof’中：
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1307：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/src/stdlib/strtod.c:1307：对‘nanf’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/Makefile.app:36: recipe for target '/home/tumblingdice/Documents/nemu/navy-apps/tests/text/build/text-am_native' failed
make[2]: *** [/home/tumblingdice/Documents/nemu/navy-apps/tests/text/build/text-am_native] Error 1
`
nemu下的:
`tumblingdice@tumblingdice-PC:~/Documents/nemu/nanos-lite$ make ARCH=x86-nemu update
Building nanos-lite [x86-nemu] with AM_HOME {/home/tumblingdice/Documents/nemu/nexus-am}
make -s -C /home/tumblingdice/Documents/nemu/navy-apps ISA=x86
+ LD /home/tumblingdice/Documents/nemu/navy-apps/apps/init/build/init-x86
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-x86.a(execr.o)：在函数‘_fork_r’中：
execr.c:(.text._fork_r+0x11)：对‘_fork’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/libs/libc/build/libc-x86.a(execr.o)：在函数‘_wait_r’中：
execr.c:(.text._wait_r+0x14)：对‘_wait’未定义的引用
/home/tumblingdice/Documents/nemu/navy-apps/Makefile.app:36: recipe for target '/home/tumblingdice/Documents/nemu/navy-apps/apps/init/build/init-x86' failed
make[2]: *** [/home/tumblingdice/Documents/nemu/navy-apps/apps/init/build/init-x86] Error 1
+ LD /home/tumblingdice/Documents/nemu/navy-apps/apps/pal/build/pal-x86
+ LD /home/tumblingdice/Documents/nemu/navy-apps/apps/litenes/build/litenes-x86
+ LD /home/tumblingdice/Documents/nemu/navy-apps/tests/bmp/build/bmptest-x86
+ LD /home/tumblingdice/Documents/nemu/navy-apps/tests/dummy/build/dummy-x86
+ LD /home/tumblingdice/Documents/nemu/navy-apps/tests/events/build/events-x86
+ LD /home/tumblingdice/Documents/nemu/navy-apps/tests/hello/build/hello-x86
+ LD /home/tumblingdice/Documents/nemu/navy-apps/tests/text/build/text-x86
`
请问一下这是怎么回事啊?

**Comment by sashimi-yzh** [comment]
請列出你的發行版版本和gcc版本

**Comment by bsblcc** [comment]
> 請列出你的發行版版本和gcc版本

deepin 15.10 x64
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 

谢谢

**Comment by sashimi-yzh** [comment]
x86-nemu的問題可以通過在`navy-apps/libs/libos/src/nanos.c`中添加如下代碼解決:
```
pid_t _fork() {
  assert(0);
  return -1;
}

pid_t _wait(int *status) {
  assert(0);
  return -1;
}
```

我這邊沒有你的環境, native的問題重現不了, 可以試試在`navy-apps/Makefile.compile`中的CFLAGS_COMMON中加入`-DNO_FLOATING_POINT`的選項, 看是否能解決問題.

**Comment by sashimi-yzh** [comment]
@bsblcc 請問問題是否已經解決呢?

**Comment by bsblcc** [comment]
> @bsblcc 請問問題是否已經解決呢?
感谢回复
如你说的, 我加入了那两个函数的定义和那个flag, native下似乎是可以编译并运行的; x86-nemu下也能成功编译, 但运行时 在memmove函数中会遇到一个movsb (opcode a4)指令, 它在nemu代码框架中没有定义, 所以我猜还是有些问题. (我现在的环境是manjaro linux x64 gcc8.3, 之前的环境下, 即使加了那个选项native也无法链接)
另外我尝试按pa0的docker debian环境, 并把我目前的项目文件clone过去, 链接时还是会有一样的问题, 少那几个函数的定义, 所以我在考虑是不是我在之前的pa中漏了一些重要步骤.

**Comment by sashimi-yzh** [comment]
函數定義問題可能是框架代碼移植newlib的時候留下來的, 今年9月的版本會統一解決, 現在你定義一下上述兩個函數就可以了, 由於PA中並不使用fork和wait, 所以不會影響後面的實驗內容.

關於movsb指令, 這可能和gcc的版本有關, 直接實現一下它也是可以的.

**Comment by bsblcc** [comment]
> 函數定義問題可能是框架代碼移植newlib的時候留下來的, 今年9月的版本會統一解決, 現在你定義一下上述兩個函數就可以了, 由於PA中並不使用fork和wait, 所以不會影響後面的實驗內容.
> 
> 關於movsb指令, 這可能和gcc的版本有關, 直接實現一下它也是可以的.

谢谢, 现在链接的问题已经解决了. movsb指令如您所说的, 我尝试用gcc 6编译, 就不会出现了. 
但我现在在尝试用nemu运行仙剑奇侠传时, 会遇到stos指令 (ab), 这次我试了gcc 6,7,8都无法避开它;  而且它和movs一样,  都用了分段机制, 但只用了一个段寄存器es, 并且似乎也没更改过值.  同时native下是可以正常运行的.
所以请问有没有办法在编译时避开这个指令, 或者不得不实现的话, 有没有什么取巧的思路? 我想是不是可以确定es初始值(我还不知道怎么做), 然后在nemu中硬编码es去寻址?
我刚刚试着把stos指令跳过, 目前能播放商标动画(极慢), 不知道游戏中会不会有影响.

**Comment by sashimi-yzh** [comment]
實現這些指令的時候, 可以當段寄存器不存在, 把它們的基地址當成0就可以了, 也就是直接用有效地址來訪存.

最好不要跳過stos, 因爲它本質上是內存寫操作, 跳過的話, 可能會導致後續執行產生錯誤.

速度慢是正常的, 因爲nemu本來就不是爲了性能目的而設計的.

**Comment by Michael1015198808** [comment]
This problem will happen if you use Ubuntu 18.04 and its default C compiler.
Mr. Yu had found a way to avoid gcc generate STOS, maybe he forget this issue, @below is his solution
#### Edit navy-apps/Makefile.compile
@@ -36,2 +36,2 @@
-  CFLAGS_COMMON = -m32 -fno-pic -fno-builtin -fno-stack-protector -fno-omit-frame-pointer -march=i386 -mstringop-strategy=unrolled_loop -fno-reorder-functions $(CFLAGS_NEWLIB)
+  CFLAGS_COMMON = -m32 -fno-pic -fno-builtin -fno-stack-protector -fno-omit-frame-pointer -march=i386 -mstringop-strategy=loop -fno-reorder-functions $(CFLAGS_NEWLIB)
   CFLAGS   += $(CFLAGS_COMMON)
Notice the compilication flag
`-mstringop-strategy`

I guess, STOS is a special command to initialize an array with some value. For example, a char array like "Hello, world!". Maybe it's considered faster in gcc, so gcc compile the project with this command. And the flag I said above force gcc to use loop to avoid STOS.
Repeat one more time, the sentence above is only my guess.
